### PR TITLE
Fix wrong vim.cmd usage + cmp-nvim-lsp breaking change

### PR DESCRIPTION
**Pull request by alkaloidbit**
Hello Rafi
A great thank you for this repo, which has literally revolutionized
the way i use nvim. 
This is my very first attempt contributing an open source project, so i hope 
i'm respecting the standards.
Thanks again

### CODE REVIEW

**Comment by rafi** [comment]
Hi there, thanks!  look's like I already fixed the first bit in lspconfig.lua,
why is the `vim.cmd.lcd` considered wrong? Looking through `:h vim.cmd` it seems ok

**Comment by alkaloidbit** [comment]
Hi rafi,

 i receive following error: 
`Error executing lua ~/.config/nvim/lua/plugins/telescope.lua:397: attemps to index field 'cmd' (a function value)` after choosing a zoxide directory via the telescope picker prompt. 
furthermore, i disagree regarding the `:h vim.cmd` line. Can you try at home to see

**Comment by alkaloidbit** [comment]
Hi rafi,

Sorry if i make myself not clear. in fact i receive the following error:
`Error executing lua ~/.config/nvim/lua/plugins/telescope.lua:397: attempt to index field 'cmd' (a function value)`  when i choose the zoxide directory in the telescope picker. For me this usage of `vim.cmd` is not right, the extension is not working. And looking throught the help for `vim.cmd` tend to give me right i think ...
Can you check at home ? Thank you and excuse my poor english please

**Comment by rafi** [comment]
I've pushed a whole new rewrite with 100% lua and lazy.nvim as package-manager.
Make sure your Neovim version is 0.8 or higher. Open a new issue if you're still experiencing issues..
Thanks!

**Pull request closed without merging**
